//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_into_Multiple_tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string Phone { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
